services:
  mycelium:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M
